### ISSUE TITLE
Power off on return long press

### ISSUE THREAD

**Issue by azaitsev** [flipperdevices/flipperzero-firmware#1276]
**Is your feature request related to a problem? Please describe.**
Sometimes I need to quickly power off the device.

**Describe the solution you'd like**
It would be nice to use long press on return button to power off device. Could you implement behaviour like on old mobile phones or mp3 players? I see long press on return is not used on main screen.

**Comment by meirpro** [comment]
I'm quite sure if you press left button and back button it shuts down...

this also might help
https://docs.flipperzero.one/basics/power#og-flipper-power-modes

i use it to preserve battery, as leaving it on without any usage, drains the battery after a few days of standby (this might be an issue worth looking into, im not sure yet, but i think its due to the animations that happen on the home screen at all times)

**Comment by azaitsev** [comment]
Transport mode — in this mode the device is supplied to users. Only the built-in RTC domain clock is powered. 
The transport mode is activated through the menu: Settings -> Power -> Power OFF.

I'd like to get this just by long press of return.

**Comment by hasmar04** [comment]
I feel like instead of powering off, holding the back button should jump back to the home screen, as this is probably more common than a full power-off.
