### ISSUE TITLE
Support for NFC NTAG203

### ISSUE THREAD

**Issue by evilpete** [flipperdevices/flipperzero-firmware#1284]
Flipper will scan NTAG215 but not the simular/simpler lesser memory NTAG203 tags

NTAG203 and the NTAG215 are from the same NTAG family of chips (Both Type 2) ( ECC signatures are not supported in the NTAG203)

**Comment by GMMan** [comment]
I can take this on after #1313 is merged. Note that NTAG203 is quite different from NTAG21x from the lack of configuration area, and is not a simple extension of original Mifare Ultralight due to the in-array counters and odd dynamic lock bytes, so there's some effort required to emulate it properly.

Edit: there's no GET_VERSION support either, so this will have to be detected by attempting to read page 41 after GET_VERSION NAKs.

**Comment by GMMan** [comment]
Ran into a little snag with this, I'm not sure where to source actual NTAG203s. The cards Adafruit sells are counterfeit NTAG213s.

**Comment by evilpete** [comment]
want me to mail you a couple??

I've been looking into it, it seems they're obsolete yet at the same time
they are  still in use everywhere.

**Comment by GMMan** [comment]
Currently asking Adafruit to confirm whether they have an inventory of any NTAG203s, but if they don't, then sure.

**Comment by GMMan** [comment]
Adafruit said their manufacturer switched chips on them, so their stock is not guaranteed to be NTAG203. I've sent you an email to the address you have on your commits.

**Comment by evilpete** [comment]
no problem I'll dig a few out and the other later today,  direct email me
the shipping address.

**Comment by skotopes** [comment]
@gornekich what do you think? Can we include it in our plans?

**Comment by GMMan** [comment]
@evilpete Got the tags, and finished up the PR.
