### ISSUE TITLE
Different SAK after NFC Dump ?

### ISSUE THREAD

**Issue by Foul** [flipperdevices/flipperzero-firmware#1632]
### Describe the bug.

i dumped my door bagde with Mifare Classic Tools on my phone and mfoc on my computer :
[Door.dmp.txt](https://github.com/flipperdevices/flipperzero-firmware/files/9389697/Door.dmp.txt)

and if i dump the same badge with flipper :
[Door.nfc.txt](https://github.com/flipperdevices/flipperzero-firmware/files/9389698/Door.nfc.txt)

SAK is not the same !?! 88 on Original Dump, 08 with Flipper

### Reproduction

make a dump with proxmark, Mifare Classic tool, mfoc or any NFC dump tool..
Check the original SAK

Dump the same thing with Flipper
Check the SAK.

### Anything else?

Vigik Reader
Intratone / Cogelec badge

**Comment by gornekich** [comment]
Thanks @Foul . Very strange behavior, we will research it

**Comment by dorianboulch** [comment]
Same thing happen to me

**Comment by AkechiShiro** [comment]
Could you provide the tag's brand ?? This doesn't happen with any tags I've had on my hands so far.
Crap you did provide it already, I have one tag that is read by a VIGIK reader and that has an anti copy protection on block 15 a value gets incremented after I use it on the first VIGIK reader. Another one, that validates the tag as well, does not do this increment.

But your issue seems not to be an anti-copy protection at all.

**Comment by dorianboulch** [comment]
I think this is related to #1468

**Comment by Astrrra** [comment]
Can you still reproduce this issue?

**Comment by Astrrra** [comment]
Closing this as inactive, please re-open if the problem persists.
