### ISSUE TITLE
FAP : Bad canvas size

### ISSUE THREAD

**Issue by csBlueChip** [flipperdevices/flipperzero-firmware#1752]
### Describe the bug.

When a FAP is loaded with `./fbt launch_app APPSRC=...` the canvas size is sometimes (but not always) set to {23x13}

### Reproduction

1. Compile [this app](https://github.com/csBlueChip/FlipperZero_plugin_howto) with './fbt launch_app APPSRC=applications/bc_demo`
2. See this screen 
![image](https://user-images.githubusercontent.com/2703385/191138260-8ab3cf7b-db60-4156-85cd-11cfa8eabb9a.png)
...IF this doesn't happen the first time, exit the app and run the `launch_app` command again (always fails the second time)

I draw specific attention to these two lines of code:
* Get canvas size : https://github.com/csBlueChip/FlipperZero_plugin_howto/blob/main/bc_demo.c#L468
* Draw frame : https://github.com/csBlueChip/FlipperZero_plugin_howto/blob/main/bc_demo.c#L126

### Target

https://github.com/flipperdevices/flipperzero-firmware/tree/60bce7b8d8f2712d985352d1e38795dd8f18f3a3

### Logs

```Text
n/a
```

### Anything else?

Workaround : After launch, exit and restart the app with the FZ keyboard

**Comment by DrZlo13** [comment]
You cannot use canvas getter like this. Also, private variables are private for a reasons.

```
state->cnvW       = canvas_width(gui->canvas);
state->cnvH       = canvas_height(gui->canvas);
```

```
// There is no 'getter' for gui->canvas
// ...this is dirty/risky, but quicker and (a LOT) easier than getting changes committed to the official API
// ...essentially, we are exposing private variables [yes, C has private variables - qv. "typedef struct Gui Gui;"]
// --> applications/gui/
#include  <gui/gui_i.h>
```

There is no means of getting the canvas from another thread, because the canvas will be changed when the GUI thread doing redraw, and getting the canvas doesn't make sense, it would be invalid. Also, you cannot be sure which of the canvases is being processed at the time the canvas is get.

Get the canvas size in the draw callback (it is called in the GUI thread context).
