### ISSUE TITLE
Bluetooth not working

### ISSUE THREAD

**Issue by Emzarii** [flipperdevices/flipperzero-firmware#1996]
### Describe the bug.

After I updated software my Bluetooth connection on flipper stopped switching on bt module, so that I cannot connect to any device via bt

### Reproduction

Do not know what to write here

**Comment by LowSkillDeveloper** [comment]
I have the similar problem after using "Bluetooth Remote".  After using it on the phone, the phone cannot connect to the flipper through the app. I solved by delete the pair in the bluetooth settings on phone and flipper and data reset of flipper application on phone. 

And I didn't use this tool anymore, because it happens every time after use.

**Comment by skotopes** [comment]
Hi guys, we need logs from flipper and your device to reproduce and fix this issue. Also device model/OS will be nice to know.

**Comment by skotopes** [comment]
There is a fix in latest dev, which also will be included in next release. Please check and reopen if your issue is still persist.

**Comment by Davidberzerk** [comment]
I have most current iOS and my flipper Bluetooth won't work since I put extreme on it I'll delete flipper and reinstall and see

**Comment by skotopes** [comment]
@Davidberzerk we don't provide support for 3rd party firmware.
