### ISSUE TITLE
Add Oregon-v-1 and wrong Humidity at Nexus-TH

### ISSUE THREAD

**Issue by oldbug62** [flipperdevices/flipperzero-firmware#2114]
### Description of the feature you're suggesting.

Is it possible to ad Oregeon-v-1 Sensor? It is availabel in the rtl_433 plugin. Thx

### Anything else?

Just an Info:

The Humidity at Nexus-TH is wrong calculated at the the Weather Plugin but also in the rtl_433 plugin.

**Comment by skotopes** [comment]
Hi. Yes, but we need RAW recording of this sensor.
Same goes for incorrect Nexus-TH readings: provide us recordings with corresponding data.

**Comment by oldbug62** [comment]
Here the files recorded with flipper, just delete the .zip
I have an rtl_sdr maybe its better to record it with that let me know what file format do you need.
[Oregon-v 1_RAW_20221210-102455.sub.zip](https://github.com/flipperdevices/flipperzero-firmware/files/10199833/Oregon-v.1_RAW_20221210-102455.sub.zip)
[Nexus-TH_RAW_20221210-105426.sub.zip](https://github.com/flipperdevices/flipperzero-firmware/files/10199834/Nexus-TH_RAW_20221210-105426.sub.zip)
[Nexus-TH_RAW_20221210-104839.sub.zip](https://github.com/flipperdevices/flipperzero-firmware/files/10199835/Nexus-TH_RAW_20221210-104839.sub.zip)
[Oregon-v 1_RAW_20221210-102957.sub.zip](https://github.com/flipperdevices/flipperzero-firmware/files/10199836/Oregon-v.1_RAW_20221210-102957.sub.zip)

**Comment by Skorpionm** [comment]
what do you mean not correct?
give your records with a photo of what the real receiver shows, so that there is something to focus on

what is the point of anonymized data

**Comment by skotopes** [comment]
What @Skorpionm is trying to say is that each file must be also labeled with real values (the one that base station shows you)

**Comment by oldbug62** [comment]
The Humidity displays 21% in the Flipper Wheater Station app. My Weatherstation show about 52-55% Humidity.

![Screenshot-20221210-141015](https://user-images.githubusercontent.com/102822666/206856898-d37f3467-17d0-4eef-be33-a66b22431685.png)

**Comment by skotopes** [comment]
@oldbug62 please match it with one of the records you've provided or provide new ones that are matched.
Otherwise we can not properly verify it.

**Comment by oldbug62** [comment]
![Screenshot-20221210-143640](https://user-images.githubusercontent.com/102822666/206857960-e045599d-67d7-4409-a367-980d7a3c0a5d.png)
[RAW_20221210-143542.sub.zip](https://github.com/flipperdevices/flipperzero-firmware/files/10200193/RAW_20221210-143542.sub.zip)

**Comment by Skorpionm** [comment]
https://github.com/flipperdevices/flipperzero-firmware/pull/2116
![IMG_20221210_212036_414](https://user-images.githubusercontent.com/85568270/206867852-a1cba77f-30f4-4951-9f6a-0853fd0df0b4.jpg)
![IMG_20221210_211804_188](https://user-images.githubusercontent.com/85568270/206867860-1b5ab559-23bb-47a4-aa0f-5ad0d27442d4.jpg)
![IMG_20221210_211610_017](https://user-images.githubusercontent.com/85568270/206867869-fc5eba07-73b1-41c4-8bbb-2da0118a0030.jpg)
If >95 =>95
If <20 =>20
otherwise completely identical to the receiver

about Oregon-v-1

 I need to write down from the flipper and with photographs what the receiver shows, 5 pieces at different temperatures and humidity

**Comment by oldbug62** [comment]
Okay, I have expressed myself incorrectly. 
The weather station does not display humidity, but the sensor transmits the humidity to the weather app of the Flipper and this does not match other displays. Maybe the sensor has a defect. Sorry

attached 5 raw files with different temperatures and pictures.

My oregeon v1 only has an indoor and outdoor temperature no humidity.
![20221210_213626](https://user-images.githubusercontent.com/102822666/206874556-0dad5c23-3f2a-47e0-a493-4867edb27632.jpg)
![20221210_212809](https://user-images.githubusercontent.com/102822666/206874558-51cb04f4-5771-4178-ab42-a6483a195bc2.jpg)
![20221210_212610](https://user-images.githubusercontent.com/102822666/206874560-60f7d4b4-3807-417f-b1dd-d2dd00929719.jpg)
![20221210_211810](https://user-images.githubusercontent.com/102822666/206874561-93d1e799-9a96-4b57-a6c2-ee1db743b1ef.jpg)
![20221210_211500](https://user-images.githubusercontent.com/102822666/206874562-4027260b-aa88-48d6-8976-c0e2db1619ef.jpg)
[RAW_20221210-213631 31,3C.sub.zip](https://github.com/flipperdevices/flipperzero-firmware/files/10200890/RAW_20221210-213631.31.3C.sub.zip)
[RAW_20221210-212819 29,0C.sub.zip](https://github.com/flipperdevices/flipperzero-firmware/files/10200891/RAW_20221210-212819.29.0C.sub.zip)
[RAW_20221210-212426 24,8C.sub.zip](https://github.com/flipperdevices/flipperzero-firmware/files/10200892/RAW_20221210-212426.24.8C.sub.zip)
[RAW_20221210-211757 22,3C.sub.zip](https://github.com/flipperdevices/flipperzero-firmware/files/10200893/RAW_20221210-211757.22.3C.sub.zip)
[RAW_20221210-211521 20,5C.sub.zip](https://github.com/flipperdevices/flipperzero-firmware/files/10200894/RAW_20221210-211521.20.5C.sub.zip)

**Comment by Skorpionm** [comment]
https://github.com/flipperdevices/flipperzero-firmware/pull/2116
add Oregon-v1 protocol

you need to test with pulling out and inserting the battery so that the sensor ID changes. you need to catch the moment when the high bit of the ID is 1 (the ID is visible in the data window) and whether the temperature will be parsed correctly.
![IMG_20221213_135059_901](https://user-images.githubusercontent.com/85568270/207285191-0421788c-aa85-4b25-92d4-3928f0d81d57.jpg)
