### ISSUE TITLE
NFC 13,56MHz EVO tag can't be read

### ISSUE THREAD

**Issue by javiercalzadaquesada** [flipperdevices/flipperzero-firmware#2588]
### Description of the feature you're suggesting.

Hello team i have this tag but can no read with flipper https://www.golmar-seguridad.es/productos/evo-tag. Any one have any idea how to read with flipper?

**Comment by Astrrra** [comment]
Hi! Does the Flipper not react to the tag at all, or does it display at least the serial number (UID) of the tag?

**Comment by mgrybyk** [comment]
The comment content was moved to https://github.com/flipperdevices/flipperzero-firmware/issues/2775

**Comment by Astrrra** [comment]
@mgrybyk Hi! This is a completely different tag, even though it's branded by the same seller. The chip inside is Mifare Plus, and in your case it looks like it's in SL1, which makes it act like Mifare Classic chip, which is supported.

This issue is for EVO tags specifically, please open a separate issue for your problem, as apart from being sold by the same seller, those two are not related in any way.

Also, please include what specific sectors the keys recovered by Detect Reader are from (e.g. Sector 3 Key A: A0A1A2A3A4A5, Sector 7 Key B: 0B8C9C1FA4A5, etc), along with everything you've included in this issue.

**Comment by Astrrra** [comment]
Closing this issue as stale. If you still need help with this type of tag - please open a new one.
