### ISSUE TITLE
Can't read Indala

### ISSUE THREAD

**Issue by docpillman** [flipperdevices/flipperzero-firmware#3046]
### Describe the bug.

Cannot read Indala. Read RAW and emulate after reading not work too.  Read with amount different firmware version . 

[RAW.zip](https://github.com/flipperdevices/flipperzero-firmware/files/12543049/RAW.zip)
![IMG_7720](https://github.com/flipperdevices/flipperzero-firmware/assets/8331657/48e993a1-a264-423c-b283-9665bb9c60dd)
![IMG_7721](https://github.com/flipperdevices/flipperzero-firmware/assets/8331657/3a7ad147-89ec-4633-8ce6-77b460475280)
![camphoto_641078858](https://github.com/flipperdevices/flipperzero-firmware/assets/8331657/982078d1-9cdb-4eb4-aba6-69603fa754a8)
![IMG_7719](https://github.com/flipperdevices/flipperzero-firmware/assets/8331657/bdb6e3d5-364e-4a74-bf58-3a8cb39118de)

### Reproduction

1. Read - Not work 
2. Read Indala PSK from extra command - Not work
3. Read RAW work ... But emulation not work 
4. Trying many times ... Reader work ! Card work !

**Comment by DrZlo13** [comment]
It's look like the long (128-bit iirc) Indala and it's not currently supported by the Flipper.

**Comment by docpillman** [comment]
Why RAW reading and emulation not work ?

**Comment by docpillman** [comment]
> It's look like the long (128-bit iirc) Indala and it's not currently supported by the Flipper.

Why RAW reading and emulation not work ?

**Comment by skotopes** [comment]
> > It's look like the long (128-bit iirc) Indala and it's not currently supported by the Flipper.
> 
> Why RAW reading and emulation not work ?

Why should it?

RFID RAW was designed for developers to check if payload contains any meaningful data and that is it.
RFID RAW data should never be used for emulation because it is not RAW, but decoded data that lost phase/clock component.

In general we know about lack of Indala 128 support. Sadly we don't have such systems available for testing, so maybe someone from community will implement it.
