### ISSUE TITLE
Feature Request: Access Flipper CLI using bluethooth Terminal

### ISSUE THREAD

**Issue by nanderer** [flipperdevices/flipperzero-firmware#3227]
### Description of the feature you're suggesting.

Hi,

its nice that its got a CLI that you can use over USB but why not also offer it using bluetooth (maybe together with badusb commands)

I tried this bluetooth terminal:

https://f-droid.org/en/packages/ru.sash0k.bluetooth_terminal/

but it didnt work.
I also tried to add a serial bluetoth interface on my laptop, did also not work. Cause it didnt, its probably not implemented.

Could you make both work?

thanks in advance!

### Anything else?

USB serial interface is not there when device is locked but its also vanished when device locks itself, maybe only vansish if no connection has been established previously...

**Comment by skotopes** [comment]
@nanderer probably you are talking about Bluetooth classic, serial profile.

Flipper Zero doesn't support Bluetooth classic, only Bluetooth Low Energy. That's why `Bluetooth terminal` is not working. Also there is no `serial profile` for BLE, it's more complicated.

At this point we are not planning to expose CLI throw BLE connection.

As for USB that disconnects itself: it is intended behavior(for basic device security) if you have PIN configured.
