### ISSUE TITLE
IR Blaster auto-detect

### ISSUE THREAD

**Issue by jamisonderek** [flipperdevices/flipperzero-firmware#3414]
### Description of the feature you're suggesting.

Add support for sending signals to IR Blaster without needing to recompile and for auto-detecting the module.

This feature is two related parts:
1) Currently when `#define INFRARED_TX_DEBUG` in `furi_hal_infrared.c` is added, the Flipper sends the IR signal to the A7 pin.  This pin is used by IR Blaster, such as the device by Rabbit Labs.  It would be great to have a setting instead of having to manually edit that line of code and recompile.  The setting would be `infrared`: `internal`, `external`.
2) Some IR Blaster, such as the one from Rabbit Labs can be automatically detected by setting the A7 pin to the internal pull-up resister and then reading the pin (which will be LOW if present or HIGH is not present).  Most devices connected to A7 will not pull the pin low (like SPI or standard inline-LED).  It would be great to update the setting to be `infrared`: `internal`, `external`, `auto-detect`.

### Anything else?

Here is my proof-of-concept that shows that the IR Blaster from Rabbit Labs can be auto-detected and used by Official firmware.  This proof-of-concept does not have the settings, it is just for private testing of the feature.

https://github.com/jamisonderek/flipper-zero-tutorials/blob/main/gpio/ir_blaster/ir-blaster.patch

**Comment by gsurkov** [comment]
Implemented in #3484. 

To enable, go to `Infrared -> GPIO Settings` and set `Signal Output` to `Detect`. The only possible option for 5V power in this case is `Auto`, which will turn 5V on in case the module has been detected.

Tested on a makeshift circuit equivalent to Rabbit Labs blaster (seemed to work well), but cannot guarantee stable module detection because we are not designing these modules and therefore are making a lot of assumptions about their internal circuitry.
