### ISSUE TITLE
Archive: Unable to rename file to name with different capitalisation

### ISSUE THREAD

**Issue by ghost** [flipperdevices/flipperzero-firmware#3478]
### Describe the bug.

Archive does not allow renaming file to the same name with a different capitalisation, probably because it includes the renamed file name in the list of already used file names.

### Reproduction

1. Open archive
3. Rename some file changing only the case of some letters
4. Click save
5. Archive prints: "This name exists! Choose another name.".

**Comment by hedger** [comment]
For FAT family filesystems, names with different capitalisation are considered equal. 
You can rename the file to a temporary name, then back to the desired one.

**Comment by CookiePLMonster** [comment]
> For FAT family filesystems, names with different capitalisation are considered equal. You can rename the file to a temporary name, then back to the desired one.

This is a valid sentiment, but then the dialog file picker is "bugged", because it does case sensitive extension comparisons:
https://github.com/flipperdevices/flipperzero-firmware/blob/dev/applications/services/gui/modules/file_browser_worker.c#L130-L140

For example, I remember trying to play a `foo.WAV` file in the WAV Player that has the file picker set up like so:
https://github.com/xMasterX/all-the-plugins/blob/dev/base_pack/wav_player/wav_player.c#L29C5-L29C42
And the file would **not** show on the list.

I think this code should instead extract the extension and use `furi_string_cmpi` to compare it case-insensitively. Or maybe `path.h` should be expanded with a function doing that internally? For example `path_cmp_filename` and `path_cmp_extension`, doing case-insensitive comparisons.

**Comment by CookiePLMonster** [comment]
Branched this issue off to a new ticket: https://github.com/flipperdevices/flipperzero-firmware/issues/3492.
