### ISSUE TITLE
Error when cloning repository

### ISSUE THREAD

**Issue by dassoff** [flipperdevices/flipperzero-firmware#3482]
### Describe the bug.

When cloning a repository, an unexpected shutdown occurs when reading a sideband package

 ![image](https://github.com/flipperdevices/flipperzero-firmware/assets/124046859/fa93ea88-d626-416b-9cb6-de483ffe7b5e)

### Reproduction

```Text
1. open git bash
2. git clone --recursive https://github.com/flipperdevices/flipperzero-firmware.git
3. get error
```

### Logs

```Text
$ git clone --recursive https://github.com/flipperdevices/flipperzero-firmware.git
Cloning into 'flipperzero-firmware'...
remote: Enumerating objects: 99588, done.
remote: Counting objects: 100% (1291/1291), done.
remote: Compressing objects: 100% (874/874), done.
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 3557 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

what could be the reason and how to fix it?

**Comment by hedger** [comment]
It's an HTTP transport error in communication between your git client and GitHub. It may be caused by issues in connectivity with your ISP, some firewall/DPI misconfiguration or similar reasons.

It has nothing to do with the sources stored in the repo. Most likely you'll get the same error when cloning other large repos from GitHub.
