### ISSUE TITLE
MIFARE DESFire Auth

### ISSUE THREAD

**Issue by grafxhen** [flipperdevices/flipperzero-firmware#3600]
### Description of the feature you're suggesting.

![signal-2024-04-17-10-39-21-907 1](https://github.com/flipperdevices/flipperzero-firmware/assets/90574451/45e8ec0b-baec-49b0-a03f-fc5b1059ac86)

Hi, as seen in the picture, I cant read the apps of my MIFARE DESFire card because it would need authentication. Is it possible to bypass or solve this in another way?

BR, Jakob

**Comment by mxcdoam** [comment]
No, if this card is not issued by you and you don't have keys - it is not possible.

**Comment by gornekich** [comment]
Hello @einsjakob 
Mf DESFire is secure protocol. Your card configured the way, you can't even read applications without authentication with master key. It's almost impossible to get master key if you don't know it.

We don't plan to support authentication with known key in nfc application, since it's very hard to develop convenient design for this task and few users know keys for their cards
