### ISSUE TITLE
Slix emulation still broken since NFC refactor

### ISSUE THREAD

**Issue by Didgitalpunk** [flipperdevices/flipperzero-firmware#3630]
### Describe the bug.

Slix2 tag emulation still does not work after refactor.
tested against a Dymo labelwriter's DRM by scanning an authentic roll's tag then placing my flipper inside the printer where the tag would be.
Pre-refactor, works as intended, printer detect the emulated roll.
Post-refactor, same tag dump, no go. new tag dump, still no go.

tested with firmwares 0.90.1 for pre-refactor version, and 0.101.2 (since released, and a few before that as well)

### Reproduction

scan roll's tag.
emulate roll tag
place flipper inside the printer against the nfc reader
pre-refactor, printer detects the roll that's emulated, post-refactor, nothing happens.

**Comment by gornekich** [comment]
@Didgitalpunk thanks for the report. Could you please specify exact model of your labelwriter and roll? We need it to reproduce the issue

**Comment by Didgitalpunk** [comment]
printer's a labelwriter 550 turbo, tested with 28x89 standard adress labels as well as 36x89 Large aderss labels

**Comment by mxcdoam** [comment]
I tried to emulate SLIX-S and Tag-It HF, both times - unsuccessful. The reader doesn't react and debug log says:
 [D][Iso15693_3Listener] Wrong CRC, buffer size: 8
and
[D][Iso15693Parser] Frame parse failed
[slix-s.log](https://github.com/flipperdevices/flipperzero-firmware/files/15197505/slix-s.log)

[tag-it.log](https://github.com/flipperdevices/flipperzero-firmware/files/15197507/tag-it.log)

**Comment by gornekich** [comment]
Hello @Didgitalpunk 

In #3652 arrived workaround for this issue. When you insert roll with tag, Dymo reads tag with password. When flipper reads the tag, it doesn't read the password, since it doesn't know it. The pre-refactored firmware version accepted any password, which is not correct from protocol implementation point of view.

The perfect solution for this issue would be separate plugin, which reads Dymo tags with password. If success, flipper stores full data with password and can fully emulate the tag. However we need to know the key derivative function for Dymo tags, which is a big task for research.

In mentioned pull request I added a workaround. You can read the tag, save it and change Capability field from Default to AcceptAllPasswords. You should do it manually editing the saved file. After that the emulation will accept any passwords sent by Dymo reader and emulation should work.

Please, update the firmware to latest dev, try the workaround and let me know if the issue persists

**Comment by Didgitalpunk** [comment]
Thanks for the potential fix! I'll try it out tomorrow, printer's at work :)

**Comment by Didgitalpunk** [comment]
Fix works, printer now detects scanned tags! ty!

**Comment by IIntuitiveNaterrey** [comment]
Hey @Didgitalpunk I hope you see this. would you be able to help me figure out what all steps you took to get this to work. I see a vague Idea of what you did, but I'm brand new to the flipper zero and NFC/RFID aside from setting up keys for offices.  
I'd like to figure out how to do this for a friend who runs a vet and they have to use dymo printers because of avimark.

**Comment by Didgitalpunk** [comment]
Don't ask me, it still doesn't work on my end xD

**Comment by IIntuitiveNaterrey** [comment]
Bummer, so no way to copy a new Dymo tag on to a fresh empty tag?

**Comment by IIntuitiveNaterrey** [comment]
@Didgitalpunk 1 more question. It seemed you were close based on context: were you using iCode SLIX2 15693 HF tags to write to?

**Comment by Didgitalpunk** [comment]
No, I wasn't. Emulation is either broken still, OR, Dymo changed something.
I'd go for the latter, but I just have no way to find out.
