### ISSUE TITLE
125kHz Card Not Reading - Images and Raw Files Attached

### ISSUE THREAD

**Issue by davewilliamstx** [flipperdevices/flipperzero-firmware#3646]
### Description of the feature you're suggesting.

Have tried two different versions of this card, not reading on Flipper. I'm not sure on source of the cards, our HOA uses them.

[Unknown RFID Card.zip](https://github.com/flipperdevices/flipperzero-firmware/files/15288222/Unknown.RFID.Card.zip)

![IMG_0804 Large](https://github.com/flipperdevices/flipperzero-firmware/assets/3608077/6940529d-0708-4a1e-abd4-1bf18650bf38)
![IMG_0805 Large](https://github.com/flipperdevices/flipperzero-firmware/assets/3608077/85148bd2-d25a-4fdc-9d7e-a42580f231f4)
![IMG_0806 Large](https://github.com/flipperdevices/flipperzero-firmware/assets/3608077/2395a35a-7cdc-4875-9c46-9a0a1f295ab7)

**Comment by skotopes** [comment]
Yep this one is RFID, payload ASK coded, should be totally doable.

**Comment by zinongli** [comment]
The reading using [flipper-raw-rfid](https://github.com/hnesk/flipper-raw-rfid) from .ask looks similar to #3336
`100000000011010010111111111111111111111011110011011100111011000011011010010111111111111111111111`
Inverting it and parsing spacers gives wiegand 26-bit format
`preamble     ??bitlen   reserved        EPf   fffffffc   cccccccc   cccccccOP  CS1        CS2`
`0111111111 0 01011010 0 00000000 0 00000000 0 01000011 0 01000110 0 01001111 0 01001011 0 10000000 0 00000000 0 0000`
`f` deontes facility code and `c` denotes card id. In this case card id is `1010001100100111` which is equal to 41767 in decimal. The same card number as printed on OP's card. 

Also long pulses are around 330 mu sec given by Flipper Lab's pulse plotter. Close enough to RF/40 clock which would give 320 mu sec. 

I'm not sure if inverting is intentional or if it is my mistake in analyzing the signal. If it is intended to be like the second sequence, then my PR #3697 should enable support for this card as well. 

@davewilliamstx : do you mind taking a photo of the reader? It might help confirming the brand and protocol of this card.

**Comment by davewilliamstx** [comment]
Sure thing, it’s pretty beat up - hope it helps.

**Comment by zinongli** [comment]
Thanks! I'm not sure if the image got through from email replies to the comment section. Would you mind upload it on github directly?

**Comment by davewilliamstx** [comment]
Ah, drat - here it is again. Cheers!
<img width="455" alt="RFID Reader" src="https://github.com/flipperdevices/flipperzero-firmware/assets/3608077/1b0a797a-6e2f-4f05-9936-8c6d7d4b4e00">

**Comment by zinongli** [comment]
Ok I'm pretty sure that's a securakey radio key reader. Should be supported once my pull request above passes through, fingers crossed.

In the meantime, if you toggle on Debug Mode, you should be able to read raw and emulate raw. I've heard of successes with securakey raw emulations. Maybe it works in your case too.

**Comment by skotopes** [comment]
Fixed in https://github.com/flipperdevices/flipperzero-firmware/pull/3697 thanks to @zinongli
